site_name: GitHub Markdown
site_description: 'A website listing all formatting options available on GitHub.'
site_author: 'Andre_601'

#
# This section uses normal HTML, so normal HTML tags and specific text like &copy; are supported
copyright: |
  Author: Andre_601 | Shared under the <a href="https://github.com/Andre601/GitHub-Markdown/blob/master/LICENSE" target="_blank">MIT License</a>
  <br>The GitHub icon is a registered Icon owned by GitHub Inc.
  <br>The copyright belongs to the original copyright-owners and no attempt at claiming the icon's copyright is made.

docs_dir: docs/

#
# These three options are optional.
repo_name: Andre601/GitHub-Markdown
repo_url: https://github.com/Andre601/GitHub-Markdown
#edit_uri: tree/master/docs # If you want the Edit option/URL to be different.

nav:
  - Welcome: index.md
  - GitHub:
    - General: github/general.md
    - "Issues, Pull requests and Discussions": github/issues-pull-requests-and-discussions.md
    - Wiki: github/wiki.md

watch:
  - theme
  - _snippets

theme:
  name: 'material'
  #
  # Uncomment the below option to use the "theme extension" option
  # to customize certain aspects of the Material Theme.
  #
  custom_dir: 'theme'
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#favicon
  favicon: 'assets/img/logo.png'
  logo: 'assets/img/logo.png'
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette
  palette:
    scheme: 'slate'
    primary: 'indigo'
    accent: 'indigo'
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#feature-flags
  features:
    #- instant
    - navigation.tabs
    - navigation.top
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#icons
  icon:
    repo: 'simple/github'
    admonition:
      note: octicons/pencil-24
      abstract: octicons/paste-24
      info: octicons/info-24
      tip: octicons/light-bulb-24
      success: octicons/check-24
      question: octicons/question-24
      warning: octicons/alert-24
      failure: octicons/x-24
      danger: octicons/zap-24
      bug: octicons/bug-24
      example: octicons/beaker-24
      quote: octicons/comment-24
    

#
# You can uncomment this line together with one of the below lines to add custom CSS to the documentation.
extra_css:
  - 'assets/css/extra.css'

extra_javascript:
  - 'assets/javascripts/mathjax.js'
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#adding-social-links
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Andre601/GitHub-Markdown'
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#adding-a-web-app-manifest
  #manifest: manifest.webmanifest

plugins:
  - search
  - redirects:
      redirect_maps:
        'github/issues-pull-requests.md': 'github/issues-pull-requests-and-discussions.md'

markdown_extensions:
  - attr_list:
  - meta:
  - markdown.extensions.admonition:
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 2-6
  - markdown.extensions.footnotes:
  #
  # Uncomment the PyMdown extension you want to use.
  # Note that some might need additional settings to be added.
  #
  # Refer to the official documentation for more info:
  # - https://facelessuser.github.io/pymdown-extensions/
  #
  #- pymdownx.arithmex:
  #- pymdownx.b64:
  #- pymdownx.betterem:
  #- pymdownx.caret:
  #- pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #- pymdownx.escapeall:
  #- pymdownx.extra:
  #- pymdownx.extrarawhtml:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  #- pymdownx.inlinehilite:
  #- pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      provider: 'github'
      user: 'Andre601'
      repo: 'GitHub-Markdown'
      normalize_issue_symbols: true
  #- pymdownx.mark:
  #- pymdownx.pathconverter:
  #- pymdownx.progressbar:
  #- pymdownx.smartsymbols:
  - pymdownx.snippets:
      base_path: _snippets
  #- pymdownx.striphtml:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde:
  - pymdownx.saneheaders:
  - pymdownx.arithmatex:
      generic: true