site_name: GitHub Markdown
site_description: 'A website listing all formatting options available on GitHub.'
site_author: 'Andre_601'
site_url: 'https://docs.andre601.ch/GitHub-Markdown/'

copyright: |
  Author: Andre_601 | Shared under the <a href="https://github.com/Andre601/GitHub-Markdown/blob/master/LICENSE" target="_blank">MIT License</a>
  <br>The GitHub icon is a registered Icon owned by GitHub Inc.
  <br>The copyright belongs to the original copyright-owners and no attempt at claiming the icon's copyright is made.

docs_dir: docs/

repo_name: Andre601/GitHub-Markdown
repo_url: https://github.com/Andre601/GitHub-Markdown

nav:
  - Welcome: index.md
  - GitHub:
    - General: github/general.md
    - "Issues, Pull requests and Discussions": github/issues-pull-requests-and-discussions.md
    - Wiki: github/wiki.md

watch:
  - theme
  - _snippets

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'assets/img/logo.png'
  logo: 'assets/img/logo.png'
  palette:
    scheme: 'github'
    primary: 'indigo'
    accent: 'indigo'
  features:
    - navigation.tabs
    - navigation.top
  icon:
    repo: 'simple/github'
    admonition:
      note: octicons/pencil-24
      abstract: octicons/paste-24
      info: octicons/info-24
      tip: octicons/light-bulb-24
      success: octicons/check-24
      question: octicons/question-24
      warning: octicons/alert-24
      failure: octicons/x-24
      danger: octicons/zap-24
      bug: octicons/bug-24
      example: octicons/beaker-24
      quote: octicons/comment-24

extra_css:
  - 'assets/css/extra.css'

extra_javascript:
  - 'assets/javascripts/mathjax.js'
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Andre601/GitHub-Markdown'

plugins:
  - search
  - redirects:
      redirect_maps:
        'github/issues-pull-requests.md': 'github/issues-pull-requests-and-discussions.md'

markdown_extensions:
  - attr_list:
  - meta:
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 2-6
  - markdown.extensions.footnotes:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      provider: 'github'
      user: 'Andre601'
      repo: 'GitHub-Markdown'
      normalize_issue_symbols: true
  - pymdownx.snippets:
      base_path: _snippets
  - pymdownx.superfences:
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde:
  - pymdownx.saneheaders:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.admonition:
      types:
        - info
        - note
        - tip
        - example
        - warning
        - extensions
        - pages
        - gh-note
        - gh-tip
        - gh-important
        - gh-warning
        - gh-caution
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.details: